# Generated by Django 4.2.1 on 2023-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_portfolio_rename_ticker_stock_symbol_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dayHigh',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='dayLow',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
