# Generated by Django 4.2.1 on 2023-06-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_dayhigh_stock_daylow_stock_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='type',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
