# Generated by Django 4.2.1 on 2023-06-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_portfolio_name_portfolio_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='dayHigh',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dayLow',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
    ]
