# Generated by Django 4.2.1 on 2023-06-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_stock_dayhigh_remove_stock_daylow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='priceTraded',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='sharesTraded',
            new_name='shares',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='change',
        ),
    ]
