# Generated by Django 4.2.1 on 2023-06-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_rename_pricetraded_ticker_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
