# Generated by Django 4.2.1 on 2023-06-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_portfolio_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='stockSymbol',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
